#!/bin/bash
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# Animations
sketchybar --animate sin 30 --bar y_offset=10 y_offset=0

sketchybar --bar height=37 \
  margin=20 \
  y_offset=10 \
  corner_radius=12 \
  blur_radius=9 \
  blur_radius=100 \
  popup.blur_radius=50 \
  position=top \
  sticky=on \
  padding_left=10 \
  padding_right=10 \
  padding_bottom=100 \
  font_smoothing=on \
  topmost=off \
  color=$BAR_COLOR \
  border_color=$BORDER_COLOR \
  border_width=1 \
  notch_width=275

# Fonts
sketchybar --default icon.font="JetBrainsMonoNL Nerd Font Propo:Bold Italic:12.0" \
  icon.color=$WHITE \
  label.font="JetBrainsMonoNL Nerd Font Propo:Bold Italic:13.0" \
  label.color=$WHITE \
  background.color=$ITEM_BG_COLOR \
  background.corner_radius=5 \
  background.height=20 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=5 \
  label.padding_right=5 \
  icon.padding_left=0 \
  icon.padding_right=0

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

source $ITEM_DIR/front_app.sh
# source $ITEM_DIR/tmux.sh
# source $ITEM_DIR/tmux_git.sh
source $ITEM_DIR/aerospace.sh

# -- Center Item --

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/media.sh
# source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####

sketchybar --update

# ------------------------------------------------------------------------------------------------
# Icon font: Hack Nerd Font
# Search for icons here: https://www.nerdfonts.com/cheat-sheet
#                          ﱦ 齃     ﮂ 爵        ﭵ     ﱦ  ﰊ 異 ﴱ אַ
